### ISSUE TITLE
Cannot find module './angular-neo4j.service'

### ISSUE THREAD

**Issue by suchetaswabhav** [webmaxru/angular-neo4j#2]
Hi,

I am implementing neo4j in my angular2+ project. And i ran this command -

**$ npm install angular-neo4j --save**

and implemented its module -

 **import { AngularNeo4jModule } from 'angular-neo4j';**

But i am facing difficulty when implementing this -

**import { AngularNeo4jService } from './angular-neo4j.service';**

i get error - Cannot find module './angular-neo4j.service'

Please help.

**Comment by vjramirez** [comment]
use instead:
**import { AngularNeo4jService } from "angular-neo4j";**

**Comment by webmaxru** [comment]
Thanks for answering!
